# Generated by Django 5.0.1 on 2024-01-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="url",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
