# Generated by Django 5.0.1 on 2024-01-28 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_order_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="dealership",
        ),
    ]
